name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - .github/workflows/pages.yml
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 12.3.4
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: SvelteKit sync
        run: pnpm svelte-kit sync
        working-directory: apps/web

      - name: Build
        run: pnpm build
        working-directory: apps/web
        env:
          BASE_PATH: '/custom-ereader'
          VITE_PAGE_PATH: '/custom-ereader'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
